-- ============================================================
-- 01_create_global_schema.sql
-- EShop global schema: canonical tables and fragmentation config.
-- Run as APP_USER=ESHOP in the Oracle Free container.
-- ============================================================

SET ECHO ON
SET SERVEROUTPUT ON

CONNECT eshop/eshop@FREEPDB1

-- Drop triggers first because they depend on the global table.
BEGIN
  FOR r IN (
    SELECT trigger_name
    FROM user_triggers
    WHERE trigger_name IN ('SYC_INSERT_LIGNE', 'SYC_DELETE_LIGNE', 'SYC_UPDATE_LIGNE')
  ) LOOP
    EXECUTE IMMEDIATE 'DROP TRIGGER ' || r.trigger_name;
  END LOOP;
END;
/

-- Drop packages and tables if the script is executed manually more than once.
BEGIN
  FOR r IN (
    SELECT object_name, object_type
    FROM user_objects
    WHERE object_name IN ('SITE1', 'SITE2')
      AND object_type = 'PACKAGE'
  ) LOOP
    EXECUTE IMMEDIATE 'DROP PACKAGE ' || r.object_name;
  END LOOP;
END;
/

BEGIN
  FOR r IN (
    SELECT table_name
    FROM user_tables
    WHERE table_name IN (
      'LIGNECOMMANDES1', 'COMMANDES1', 'PRODUITS1', 'CLIENTS1',
      'LIGNECOMMANDES2', 'COMMANDES2', 'PRODUITS2', 'CLIENTS2',
      'LIGNECOMMANDES', 'COMMANDES', 'PRODUITS', 'CLIENTS',
      'FRAGMENTATION_CONFIG'
    )
  ) LOOP
    EXECUTE IMMEDIATE 'DROP TABLE ' || r.table_name || ' CASCADE CONSTRAINTS PURGE';
  END LOOP;
END;
/

-- Active scenario table.
-- SCENARIO = 1:
--   Site1: category 50 and quantity > 100
--   Site2: category 35 and quantity > 50
-- SCENARIO = 2:
--   Site1: quantity >= 100
--   Site2: quantity < 100
CREATE TABLE Fragmentation_Config (
  id_config NUMBER GENERATED BY DEFAULT AS IDENTITY,
  scenario NUMBER(1) DEFAULT 1 NOT NULL,
  updated_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT pk_fragmentation_config PRIMARY KEY (id_config),
  CONSTRAINT ck_fragmentation_scenario CHECK (scenario IN (1, 2))
);

INSERT INTO Fragmentation_Config (scenario) VALUES (1);

CREATE TABLE Clients (
  idclient NUMBER NOT NULL,
  codeclient VARCHAR2(20) NOT NULL,
  societe VARCHAR2(120) NOT NULL,
  contact VARCHAR2(120),
  ville VARCHAR2(80),
  pays VARCHAR2(80),
  telephone VARCHAR2(30),
  CONSTRAINT pk_clients PRIMARY KEY (idclient),
  CONSTRAINT uk_clients_code UNIQUE (codeclient)
);

CREATE TABLE Produits (
  idproduit NUMBER NOT NULL,
  idcateg NUMBER NOT NULL,
  designation VARCHAR2(160) NOT NULL,
  prixunitaire NUMBER(10, 2) NOT NULL,
  CONSTRAINT pk_produits PRIMARY KEY (idproduit),
  CONSTRAINT ck_produits_prix CHECK (prixunitaire >= 0)
);

CREATE TABLE Commandes (
  idcommande NUMBER NOT NULL,
  idemploye NUMBER NOT NULL,
  idclient NUMBER NOT NULL,
  datecommande DATE NOT NULL,
  adresse_livraison VARCHAR2(200),
  ville_livraison VARCHAR2(80),
  pays_livraison VARCHAR2(80),
  CONSTRAINT pk_commandes PRIMARY KEY (idcommande),
  CONSTRAINT fk_commandes_clients FOREIGN KEY (idclient)
    REFERENCES Clients (idclient)
);

CREATE TABLE LigneCommandes (
  idlignecommande NUMBER NOT NULL,
  idcommande NUMBER NOT NULL,
  idproduit NUMBER NOT NULL,
  quantite NUMBER NOT NULL,
  remise NUMBER(5, 4) DEFAULT 0 NOT NULL,
  CONSTRAINT pk_lignecommandes PRIMARY KEY (idlignecommande),
  CONSTRAINT fk_ligne_commandes FOREIGN KEY (idcommande)
    REFERENCES Commandes (idcommande),
  CONSTRAINT fk_ligne_produits FOREIGN KEY (idproduit)
    REFERENCES Produits (idproduit),
  CONSTRAINT ck_ligne_quantite CHECK (quantite > 0),
  CONSTRAINT ck_ligne_remise CHECK (remise >= 0 AND remise < 1)
);

COMMIT;
